name: Renaissance
version: ${version}
description: ${description}
authors: [molenzwiebel, Komp, skreem, TeddyTheTeddy]
main: net.hungerstruck.renaissance.RenaissancePlugin
api-version: 1.13

commands:
   debug:
       description: This should be removed.
       permission: renaissance.admin
       usage: Enter a script idiot.

permissions:
  renaissance.admin:
    default: op
